version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    auto-merge: true
    # 默认：5
    # 设置为 1，防止 @typescript-eslint/parser、@typescript-eslint/parser 更新时出现冲突
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: typescript
        versions:
          - ">= 5"
